### PR TITLE
Fix result cannot highlight when using ripgrep

### PR DESCRIPTION
**Pull request by junhuihuang**
`\( func` cannot highlight when using ripgrep, and get error: 
> error in process sentinel: Invalid regexp: "Unmatched ( or \\("

### CODE REVIEW

**Comment by syohex** [comment]
Sorry very late reply. Looks good.

However it is better to rename `helm-ag--pcre-to-elisp-regexp` as below

```diff
diff --git a/helm-ag.el b/helm-ag.el
index 88f4949..bd2de36 100644
--- a/helm-ag.el
+++ b/helm-ag.el
@@ -192,7 +192,7 @@ Default behaviour shows finish and result in mode-line."
     (when helm-ag-use-emacs-lisp-regexp
       (setq query (helm-ag--elisp-regexp-to-pcre query)))
     (setq helm-ag--last-query query
-          helm-ag--elisp-regexp-query (helm-ag--pcre-to-elisp-regexp query))
+          helm-ag--elisp-regexp-query (helm-ag--convert-to-elisp-regexp query))
     (setq helm-ag--valid-regexp-for-emacs
           (helm-ag--validate-regexp helm-ag--elisp-regexp-query))
     (if (not options)
@@ -351,10 +351,10 @@ Default behaviour shows finish and result in mode-line."
         t)
     (invalid-regexp nil)))
 
-(defun helm-ag--pcre-to-elisp-regexp (pcre)
+(defun helm-ag--convert-to-elisp-regexp (regexp)
   ;; This is very simple conversion
   (with-temp-buffer
-    (insert pcre)
+    (insert regexp)
     (goto-char (point-min))
     ;; convert (, ), {, }, |
     (while (re-search-forward "[(){}|]" nil t)
@@ -887,7 +887,7 @@ Continue searching the parent directory? "))
 (defun helm-ag--do-ag-highlight-patterns (input)
   (if (or (memq 'pcre helm-ag--command-features)
           (memq 're2 helm-ag--command-features))
-      (cl-loop with regexp = (helm-ag--pcre-to-elisp-regexp input)
+      (cl-loop with regexp = (helm-ag--convert-to-elisp-regexp input)
                for pattern in (helm-ag--split-string regexp)
                when (helm-ag--validate-regexp pattern)
                collect pattern)

```

**Comment by kiennq** [comment]
I hope we can get this merged, I'm using ripgrep since it's faster and suffer badly without this

**Comment by jcs090218** [comment]
@junhuihuang Ping! :)

**Comment by jcs090218** [comment]
Close this issue now, see #347

**Pull request closed without merging**
