### PR TITLE
Added optional default search term in helm-do-ag.

### PR DESCRIPTION
**Pull request by cibinmathew**
Added an optional parameter to supply default search term in helm-do-ag function.

### CODE REVIEW

**Comment by cibinmathew** [comment]
Can this be merged

**Comment by syohex** [comment]
Sorry very late reply. Looks good except following function argument. I suppose its argument needs not be optional argument.

https://github.com/emacsorphanage/helm-ag/blob/4f0887f0ed73598b6b01eeabb05871b30b0c451c/helm-ag.el#L1111

**Comment by cibinmathew** [comment]
> Sorry very late reply. Looks good except following function argument. I suppose its argument needs not be optional argument.
> 
> https://github.com/emacsorphanage/helm-ag/blob/4f0887f0ed73598b6b01eeabb05871b30b0c451c/helm-ag.el#L1111

I guess, If it is not made optional, existing configurations of all users can throw error.

**Comment by syohex** [comment]
I suppose it is private function,users should not depend on its signature changing.

**Comment by jcs090218** [comment]
I suppose this can be merged. Thanks!

**Pull request merged**
