### PR TITLE
Add syohex's patch for incremental coloring

### PR DESCRIPTION
**Pull request by jimeh**
Patch source: https://github.com/emacsorphanage/helm-ag/issues/305#issuecomment-622924494

Allows results to be colored immediately as they are displayed, instead
of coloring being applied after all results are found which can take a
while when searching large directories.

---

I've only tested these changes myself for a few minutes, but they seem to work, and haven't caused any issues for me. Obviously I'm not the author of the code, just found it useful enough to put together a PR, so please let me know if something is not right or needs changing :)

/cc @syohex

### CODE REVIEW

**Comment by jcs090218** [comment]
This looks good! Merged now! Thanks for the contribution! :)

**Comment by Davidj361** [comment]
Thank you so much! It's finally not janky.

**Comment by mikloq** [comment]
git bisect sys this commit breaks (C-l) helm-ag--up-one-level since it does not work any longer , reverting it fixes the issue.

**Comment by jcs090218** [comment]
@mikloq Can you open in another issue? Thanks!

Very sorry that this patch breaks the command `helm-ag--up-one-level`. The best solution will have to figure out the bug from the current `master` branch. If it doesn't go well, we might have to revert it then! :(

**Pull request merged**
