### PR TITLE
Add double dash for default searched things

### PR DESCRIPTION
**Pull request by pkryger**
I found myself using this package (via `(projectile-helm-ag)`) a lot.
However, I very often have a need to search for symbols that start
with `-`. And I use `(thing-at-point)` method to get the string. Without
this commit this results in

```
Candidates function ‘helm-ag--do-ag-candidate-process’ should run a process
```

I decided to fix that by preppending the search term, being it a selected text
or `(thing-at-point)`, with `--` to follow what is in readme.

Run tests from the `test-util.el` - they all pass. Quickly skimming the file
I haven't seen anything targeted to `(helm-do-ag)` nor `(helm-do-ag--helm)`.

### CODE REVIEW

**Comment by arichiardi** [comment]
Awesome, I will try this out as well

**Comment by syohex** [comment]
sorry very late reply. This looks good except one thing. You should use `concat` or `cl-concatenate` instead of `concatenate` because `concatenate` is cl.el function and it is deprecated on newer emacs. I suppose it is enough to use `concat` in this case. `concat` is a function in standard library.

```diff
diff --git a/helm-ag.el b/helm-ag.el
index 7436f9f..d3c6a61 100644
--- a/helm-ag.el
+++ b/helm-ag.el
@@ -1120,7 +1120,7 @@ Continue searching the parent directory? "))
           :input (let ((input (or (helm-ag--marked-input t)
                                   (helm-ag--insert-thing-at-point helm-ag-insert-at-point))))
                    (if (string-prefix-p "-" input)
-                       (concatenate 'string "-- " input)
+                       (concat "-- " input)
                      input))
           :history 'helm-ag--helm-history)))
```

whole patch is as bellow

```diff
diff --git a/helm-ag.el b/helm-ag.el
index eb32316..d3c6a61 100644
--- a/helm-ag.el
+++ b/helm-ag.el
@@ -1117,8 +1117,11 @@ Continue searching the parent directory? "))
     (helm-attrset 'name (helm-ag--helm-header search-dir)
                   helm-source-do-ag)
     (helm :sources '(helm-source-do-ag) :buffer "*helm-ag*" :keymap helm-do-ag-map
-          :input (or (helm-ag--marked-input t)
-                     (helm-ag--insert-thing-at-point helm-ag-insert-at-point))
+          :input (let ((input (or (helm-ag--marked-input t)
+                                  (helm-ag--insert-thing-at-point helm-ag-insert-at-point))))
+                   (if (string-prefix-p "-" input)
+                       (concat "-- " input)
+                     input))
           :history 'helm-ag--helm-history)))
 
 ;;;###autoload
```

**Comment by pkryger** [comment]
@syohex I've made the change and merged with master. Could you please review it?

**Comment by syohex** [comment]
Looks good. However I no longer maintain this package. Please wait until merging this PR by current maintainer.

**Comment by jcs090218** [comment]
@pkryger Thanks for your contribution! :)

@syohex Do you still want to maintain this package? It seems like you still interested in maintaining it! Anyway, thanks for spending time on reviewing PRs! 😄

**Comment by syohex** [comment]
> Do you still want to maintain this package?

no

**Pull request merged**
